server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        #Nacos服务注册中心地址
        server-addr: localhost:8848
#        metadata:
#          gRPC:
#            port:

    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080   #本地
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
#        clientIp: 10.10.231.225
#      web-context-unify: false


      datasource:
        ds:  #添加nacos数据源的配置，将sentinel配置持久化进nacos里面
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            username: nacos
            password: nacos
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'




